#!/bin/bash

#SBATCH --job-name=SFDA
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --mem=70GB
#SBATCH --time=15:00:00
#SBATCH --gres=gpu
#SBATCH --partition=a100_1,a100_2,v100,rtx8000

# job info
train_file=$1
config_path=$2
exp_name=$3
exp_id=$4

# Singularity path
ext3_path=/scratch/$USER/my_env/py10/overlay-25GB-500K.ext3
sif_path=/scratch/$USER/my_env/cuda11.4.2-cudnn8.2.4-devel-ubuntu20.04.3.sif

# start running
singularity exec --nv \
--overlay ${ext3_path}:ro \
${sif_path} /bin/bash -c "
source /ext3/env.sh
cd /scratch/$USER/Research-Team/NRC_My
python -m src.${train_file} --config ${config_path} --exp_name ${exp_name} --exp_id ${exp_id}
"
